services:
  minio:
    image: minio/minio
    container_name: minio
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadminpassword
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./data/minio:/data
      
  cassandra-seed:
    image: cassandra:4.1.9
    container_name: cassandra-seed
    environment:
      - CASSANDRA_CLUSTER_NAME=remsfal-cassandra-cluster
      - CASSANDRA_NUM_TOKENS=8
      - CASSANDRA_SEEDS=cassandra-seed
      - CASSANDRA_USER=admin
      - CASSANDRA_PASSWORD=admin
    ports:
      - "9042:9042"
      - "7000:7000"

  cassandra-node1:
    image: cassandra:4.1.9
    container_name: cassandra-node1
    environment:
      - CASSANDRA_CLUSTER_NAME=remsfal-cassandra-cluster
      - CASSANDRA_SEEDS=cassandra-seed
    ports:
      - "9043:9042" # Alternative port mapping for node1
      - "7001:7000"

  kafka:
    image: apache/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
