services:
  minio:
    image: minio/minio
    container_name: minio
    environment:
      - MINIO_ROOT_USER=remsfal
      - MINIO_ROOT_PASSWORD=remsfal
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./data/minio:/data
      
  cassandra:
    image: cassandra:4
    container_name: cassandra
    environment:
      - CASSANDRA_CLUSTER_NAME=remsfal-cassandra-cluster
      - CASSANDRA_NUM_TOKENS=8
      - CASSANDRA_SEEDS=cassandra
      - CASSANDRA_USER=remsfal
      - CASSANDRA_PASSWORD=remsfal
    ports:
      - "9042:9042"

  ocr:
    image: ghcr.io/remsfal/remsfal-ocr:latest
    container_name: remsfal-ocr
    depends_on:
      - kafka-broker
      - minio
    environment:
      - KAFKA_BROKER=kafka-broker:29092
      - MINIO_ENDPOINT=minio:9000
      - PYTHONUNBUFFERED=1
