services:
  mysql:
    image: mysql:lts
    container_name: mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=REMSFAL
    ports:
      - "3306:3306"

  zeebe:
    image: camunda/zeebe:latest
    container_name: camunda
    environment:
      - ZEEBE_BROKER_CLUSTER_SIZE=1
      - ZEEBE_BROKER_PARTITIONS_COUNT=1
      - ZEEBE_BROKER_REPLICATION_FACTOR=1
    ports:
      - "26500:26500"
